# Generated by Django 4.2.6 on 2023-11-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('conform_password', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
