# Generated by Django 4.2.6 on 2023-11-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_registration_user_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='lists',
        ),
    ]
