# Generated by Django 4.2.6 on 2023-11-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_todolist_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='todoTypes',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
